name          'garethr-diamond'
version       '0.6.0'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to manage the Diamond stats collection tool'
project_page  'https://github.com/garethr/garethr-diamond'
